import './globals.css';
import { Montserrat } from 'next/font/google';
import React from 'react';

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={montserrat.className}>{children}</body>
        </html>
    );
}
