import './globals.css';
import { Montserrat } from 'next/font/google';
import React from 'react';
import { NextIntlClientProvider } from 'next-intl';
import { getTranslation } from '@/lib/utils/translation';
import { LayoutProps } from '@/lib/types/types';

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
    params: { locale },
}: LayoutProps) {
    const translation = await getTranslation(locale);

    return (
        <html lang={locale}>
            <NextIntlClientProvider locale={locale} messages={translation}>
                <body className={montserrat.className}>{children}</body>
            </NextIntlClientProvider>
        </html>
    );
}
