import './globals.css';
import { Montserrat } from 'next/font/google';
import React from 'react';
import { NextIntlClientProvider, useLocale } from 'next-intl';
import { LayoutProps } from '@/lib/types';
import Footer from '@/components/layout/footer/Footer';
import getRequestConfig from '@/i18n';
import Header from '@/components/layout/header/Header';
import { Providers } from '@/lib/providers';
import CookieBanner from '@/components/banners/cookie/CookieBanner';

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: LayoutProps) {
    const locale = useLocale();
    const { messages } = await getRequestConfig({ locale });

    return (
        <html lang={locale}>
            <NextIntlClientProvider locale={locale} messages={messages}>
                <Providers>
                    <body className={montserrat.className}>
                        <CookieBanner />
                        <Header />
                        <main>{children}</main>
                        <Footer />
                    </body>
                </Providers>
            </NextIntlClientProvider>
        </html>
    );
}
